apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wordpress-db
  namespace: wordpress
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secretmanager
    kind: SecretStore

  target:
    name: wordpress-db

  data:
  - secretKey: password
    remoteRef:
      key: wordpress-db-password
