name: Terraform Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
      - ".github/workflows/infra.yml"

  pull_request:
    branches:
      - main
    paths:
      - "infra/**"

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TF_IN_AUTOMATION: true

jobs:

  terraform:

    name: Terraform Infra

    runs-on: ubuntu-latest

    environment: production

    defaults:
      run:
        working-directory: infra

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    ##################################################
    # Google Authentication
    ##################################################

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GITHUB_ACTIONS_SA }}

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    ##################################################
    # Terraform
    ##################################################

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.15.8

    - name: Terraform Format
      run: terraform fmt -recursive -check

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan
        path: infra/tfplan

    ##################################################
    # Apply only on Main Branch
    ##################################################

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
